kind = "web"
previewPath = "/"
title = "Finventory"
version = "1.0.0"
id = "artifacts/finventory"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22962

[services.development]
run = "pnpm --filter @workspace/finventory run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/finventory", "run", "build" ]
publicDir = "artifacts/finventory/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22962"
BASE_PATH = "/"
